### ISSUE TITLE
config.val_data.batch_size is not defined

### ISSUE THREAD

**Issue by itsrifat** [zhangxiangxiao/Crepe#1]
`config.train_data.batch_size` is defined twice at [Line 18](https://github.com/zhangxiangxiao/Crepe/blob/master/train/config.lua#L18) and [Line 25](https://github.com/zhangxiangxiao/Crepe/blob/master/train/config.lua#L25) in `train/config.lua` . Looks like the seconds one is supposed to be `config.val_data.batch_size` ?

**Comment by zhangxiangxiao** [comment]
Fixed
