### ISSUE TITLE
[Question] Where is batch Tensor initialized?

### ISSUE THREAD

**Issue by gheinrich** [zhangxiangxiao/Crepe#10]
Sorry for the dumb question I must have missed something but I fail to see where the `Tensor` used to store batch data is initialized in this [function](https://github.com/zhangxiangxiao/Crepe/blob/master/train/data.lua#L56)? I can see how the one "bit" corresponding to each character is set in `stringToTensor` but don't you need to explicitly zero-initialize the tensor on that [line](https://github.com/zhangxiangxiao/Crepe/blob/master/train/data.lua#L59)?

**Comment by Schrodinger1926** [comment]
[here](https://github.com/zhangxiangxiao/Crepe/blob/master/train/data.lua#L59)

**Comment by gheinrich** [comment]
Thanks. My question was: where do we initialize _the contents_ of the tensor? In my understanding the line you pointed at creates a tensor with undefined contents.

**Comment by gheinrich** [comment]
Oh, it's [there](https://github.com/zhangxiangxiao/Crepe/blob/master/train/data.lua#L157) sorry!
