### ISSUE TITLE
[Question] Would using ReLU instead of Threshold produce similar results?

### ISSUE THREAD

**Issue by marcbelmont** [zhangxiangxiao/Crepe#14]
Hi, I've noticed that in the model you are using Threshold instead of ReLU. What is the reason behind this choice?

If I'm reading the source correctly, the only difference between those is that Thresold has self.threshold initialized at 1e-6 instead of 0 for ReLU [1]. Is this affecting the success of the model in a significant way?

[1] https://github.com/torch/nn/blob/master/ReLU.lua

**Comment by zhangxiangxiao** [comment]
I do not think there will be any noticeable difference. You can try.

At the time I programmed the models in this repository there was no ReLU.lua in my torch install. They added it in late 2014.

**Comment by marcbelmont** [comment]
Thanks for the answer.

**Comment by sivagnanamn** [comment]
@marcbelmont Hi, did you try using ReLU instead of Threshold?? Is there any improvement?

**Comment by marcbelmont** [comment]
@sivagnanamn nope, I did not try it.
