### ISSUE TITLE
Unable to connect X11 server

### ISSUE THREAD

**Issue by ziaoang** [zhangxiangxiao/Crepe#15]
When I run the main.lua by 'qlua main.lua', I got bugs like below:

```
Unable to connect X11 server (continuing with -nographics)
Device set to 1
Loading datasets...
Loading the model...
Model randomized.
Current model type: torch.CudaTensor
Loading the trainer...
Loading the tester...
qlua: not loading module qtuiloader (running with -nographics)
qlua: not loading module qtgui (running with -nographics)
qlua: qtwidget window functions will not be usable (running with -nographics)
qtwidget window functions will not be usable (running with -nographics)
qlua: ./scroll.lua:16: attempt to index global 'qtuiloader' (a nil value)
stack traceback:
    [C]: in function '__index'
    ./scroll.lua:16: in function '__init'
    ...ysfeng/lvchao/torch/install/share/lua/5.1/torch/init.lua:91: in function <...ysfeng/lvchao/torch/install/share/lua/5.1/torch/init.lua:87>
    [C]: in function 'Scroll'
    ./mui.lua:21: in function '__init'
    ...ysfeng/lvchao/torch/install/share/lua/5.1/torch/init.lua:91: in function <...ysfeng/lvchao/torch/install/share/lua/5.1/torch/init.lua:87>
    [C]: in function 'Mui'
    main.lua:123: in function 'new'
    main.lua:41: in function 'main'
    main.lua:316: in main chunk
'''
How can I remove the ui show?
```

**Comment by koalaGreener** [comment]
I've got exactly the same problem. Hope to fix it soon.

**Comment by zhangxiangxiao** [comment]
You can disable visualization by removing the requirements for gnuplot and mui in main.lua, and remove all calls to main.show and main.draw.

**Comment by awaiskhan2007** [comment]
In case, if you dont want to remove UI requirements, Xming Server together with putty using X11 forwarding will resolve your issue; if still you get the same error; then you might need to re-install your GPU drivers and torch;

**Comment by flaviopol** [comment]
Hi, I did this "You can disable visualization by removing the requirements for gnuplot and mui in main.lua, and remove all calls to main.show and main.draw." I trained and now I have the results on the files main_EPOCHES_TIME.t7b and sequential_EPOCHES_TIME.[t7b|png]. The question is, How can I visualize these results? e.g. The confusion matrix. Thanks.
