### ISSUE TITLE
Printing classes

### ISSUE THREAD

**Issue by ch3njust1n** [zhangxiangxiao/Crepe#17]
I was told that I can used test.decision[i] to see the classes Crepe outputs.
Would I print out test.decision[i] in main.lua?
Also is there a way to associate the i-th input with test.decision[i]?
Can I do the same for training?

**Comment by zhangxiangxiao** [comment]
It's the same for training. Read the code please.

**Comment by ch3njust1n** [comment]
Sorry for asking again, I've read through the code, but I can't seem to figure out how to get the predicted labels for both training and testing other than printing out the decision variable. However, when I print out the decision variable I'm not getting as many inputs as I put in. Did you mean there's some way for viewing the labels in the .t7b files in the terminal? Again sorry for asking this again.

**Comment by zhangxiangxiao** [comment]
No the labels are not saved any where.

Each time decision[i] contains the label of the i-th sample in **current batch**. Test.lua loop over all samples with many batches.

You may want to save these decisions to a file by writing some code.

**Comment by ch3njust1n** [comment]
Ok cool. That's what I did. Just wasn't sure if I was correct. 
Thanks again!
