### ISSUE TITLE
Y-axis scale and units?

### ISSUE THREAD

**Issue by ch3njust1n** [zhangxiangxiao/Crepe#19]
I just want to verify that my network is working correctly and that I'm interpreting the graphs correctly on my own data. I was tinkering around with the code before launching it, so not sure if I accidentally messed up somewhere. Several questions:
1. For loss, I got values over 1 for validation. How bad is that? Is a loss over 1 big or is it reasonable?
2. Is the error y-axis unit in percent? So here, for the error, would it range from 0% to 0.16% or is it 0% to 16%? ![crepe-10000-error](https://cloud.githubusercontent.com/assets/3211697/17590117/624bafd2-5fa6-11e6-8725-5f9c6f4ff902.png)
   ![crepe-10000-loss](https://cloud.githubusercontent.com/assets/3211697/17590123/672b69c0-5fa6-11e6-8be1-d5280336b4d7.png)
3. When I trained on the dbpedia_csv data, the loss and error graphs looked about the same shape. In general, should the loss and error graphs always have the same shape?
4. Are the error and loss on different scales?

![crepe_output](https://cloud.githubusercontent.com/assets/3211697/17590280/2bc62b1c-5fa7-11e6-9fb4-e6d68f28b161.png)

Apologies again, Zhang, for all the questions.

**Comment by zhangxiangxiao** [comment]
The error plot is normalized to 1. When you see the error 0.05, it means error at 5%.

The loss plot is the value of the optimization objective, lower-bounded by 0 but not upper-bounded.
