### ISSUE TITLE
error running example code

### ISSUE THREAD

**Issue by Zhen-hao** [zhangxiangxiao/Crepe#2]
When I run $ qlua main.lua, I get the following error message:

dyld: Library not loaded: @rpath/./libQtGui.4.dylib
  Referenced from: /usr/local/bin/qlua
  Reason: image not found
Trace/BPT trap: 5

My environment: os x 10.10.5, torch7, lua 5.1.4, xcode 6.2

**Comment by zhangxiangxiao** [comment]
It seems like Qt is missing or qtlua is not installed correctly.

**Comment by elbamos** [comment]
Did you ever solve this?  I'm having the same issue.  Presumably we both used the same set of installation instructions...

**Comment by Zhen-hao** [comment]
No, I haven't solved it. It seems that I couldn't install the qtlua package. The installation doesn't generate error messages but requiring the package does.

**Comment by Zhen-hao** [comment]
I solved this problem by installing QT. Thanks!

**Comment by elbamos** [comment]
I ultimately solved it as well -- it seems it was caused by having existing homebrew installations of some of the deps, but I was never able to pin in down precisely.
