### ISSUE TITLE
Yelp dataset

### ISSUE THREAD

**Issue by Hrant-Khachatrian** [zhangxiangxiao/Crepe#27]
How is the Yelp dataset constructed?
The paper mentions that there are 1.5M+ samples in the original dataset, but you used 280K + 19K samples for the polarity version. How did you construct these small ones? Are they available for download?

Thanks!

**Comment by zhangxiangxiao** [comment]
The download link is available in the repo readme

**Comment by Hrant-Khachatrian** [comment]
Thanks, didn't notice it
