### ISSUE TITLE
duplicate hyphen (minus?) in alphabeta?

### ISSUE THREAD

**Issue by pengsun** [zhangxiangxiao/Crepe#4]
In `train/config.lua`, there are two hyphens (minus) in `alphabeta`:
... 9-, ...
and
 ... +-= ...

Is it intentional? If not, does it affect the convnet size specs?

**Comment by Schrodinger1926** [comment]
I think this is unintentional, and yes this affects the input frame size.

**Comment by zhangxiangxiao** [comment]
I did not even realize that, until now
