### ISSUE TITLE
Not able to understant where you did preprocessing of text?

### ISSUE THREAD

**Issue by sonuauti** [zhangxiangxiao/Crepe#6]
Hi, which module is responsible for preprocessing of input text?

**Comment by Schrodinger1926** [comment]
Well, @cispune , this is the point. It doesn't need any pre-processing. The only thing which has been altered in the text is that all the uppercase letters are converted to lower ones  which can be seen in `csv2t7b.lua`. Everything else including all the special characters and numbers are fed directly in the network. The purpose is to build it from scratch.
