### ISSUE TITLE
Attempt to call field 'TemporalConvolution_updateOutput' (a nil value)

### ISSUE THREAD

**Issue by MdAsifKhan** [zhangxiangxiao/Crepe#8]
I am using [Crepe](https://github.com/zhangxiangxiao/Crepe) for my sequential data. On executing main.lua the following error appears:
qlua: ...b/torch/install/share/lua/5.1/nn/TemporalConvolution.lua:41: attempt to call field 'TemporalConvolution_updateOutput' (a nil value)
stack traceback:
    [C]: in function 'TemporalConvolution_updateOutput'
    ...b/torch/install/share/lua/5.1/nn/TemporalConvolution.lua:41: in function 'updateOutput'
    ...e/user/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    ./model.lua:30: in function 'forward'
    ./train.lua:89: in function 'batchStep'
    ./train.lua:68: in function 'run'
    main.lua:140: in function 'run'
    main.lua:42: in function 'main'
    main.lua:316: in main chunk

Is it some kind of a bug or any specific change is to be done with the configuration?

Thanks,
Asif

**Comment by zhangxiangxiao** [comment]
Try removing torch and reinstall. They recently updated the way how the package nn is structured. See here: https://github.com/torch/nn/commit/1973b799c4a37ad82d01de163f27e40ebe03bfa3

**Comment by MdAsifKhan** [comment]
Thanks, it works now!
