### ISSUE TITLE
Issue in saving data

### ISSUE THREAD

**Issue by MdAsifKhan** [zhangxiangxiao/Crepe#9]
The networks executes well but after completing all the era it get's stuck and just displays 'Saving data' and doesn't complete the execution.

**Comment by Schrodinger1926** [comment]
Paste it here, lets have a look

**Comment by MdAsifKhan** [comment]
It get stuck at following point and doesn't complete the execution.
Recording on era 100
Visualizing loss
Visualizing the models
Saving data

**Comment by zhangxiangxiao** [comment]
I too encountered some occasions of a torch progress hanging without exiting. After printing 'saving data' for several minutes the file is already saved, but it hangs without doing anything. CNTRL + C might be needed to exit the program.

I did not yet know why this occurs.

**Comment by zhangxiangxiao** [comment]
Update:
One possible reason for this to occur is because you have a hanging Qt window. Our visualization module uses Qt for that. You may want to manually close the Qt window to complete the last running era.
